# Generated by Django 3.0.7 on 2021-07-24 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('snip_app', '0002_auto_20210724_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snip',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
