# Generated by Django 3.0.7 on 2021-07-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snip_app', '0003_auto_20210724_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snip',
            name='lang',
        ),
    ]
