# Generated by Django 3.0.7 on 2021-07-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snip_app', '0004_remove_snip_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snip',
            name='link_code',
        ),
    ]
